services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://core-service:4000
      - REACT_APP_AUTH_URL=http://auth-service:5000
      - REACT_APP_WS_URL=ws://chat-service:7000
    depends_on:
      - auth-service
      - core-service
      - chat-service

  auth-service:
    build: ./auth-service
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET=supersecretkey
      - DB_URL=postgresql://user:password@db/auth
    depends_on:
      - db

  core-service:
    build: ./core-service
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://user:password@db/core
      - MINIO_ENDPOINT=minio
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=3dprints
    depends_on:
      - db
      - minio

  chat-service:
    build: ./chat-service
    ports:
      - "7000:7000"

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio
    command: server /data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data

  minio-setup:
    build: ./minio-setup
    depends_on:
      - minio

volumes:
  pgdata:
  minio_data: